language: nodejs

node_js:
  - "node"

cache: yarn

before_script:
  - yarn install
  - node node_modules/.bin/tsc
  - cp package.json dist
  - cp src/router.php dist
  - cp README.md dist
  - cp LICENSE dist
  - cd dist

script:
  - node index.js --help
  - node index.js build --help
  - node index.js serve --help

before_deploy:
  - yarn pack

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "wp-builder-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "0x6368656174@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
