language: nodejs

node_js:
  - "node"

cache: yarn

before_script:
  - yarn install
  - npm run build
  - node utils/create-package.json.js
  - cp src/router.php dist
  - cp README.md dist
  - cp LICENSE dist
  - cp -r src/starter dist
  - cd dist

script:
  - node index.js --help
  - node index.js build --help
  - node index.js serve --help

before_deploy:
  - yarn pack

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "0x6368656174-wp-builder-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    api_key: $NPM_TOKEN
    email: "0x6368656174@gmail.com"
    skip_cleanup: true
    on:
      tags: true
