import * as webpack from 'webpack';

export class TimberFixPlugin {
  public static getContent() {
    return  `
/** AUTO GENERATED BY timber-fix.plugin **/
use Timber\\URLHelper;
use Timber\\Theme;

add_filter('timber/context', function ($context) {
  /** @var Theme $theme */
  $theme = $context['theme'];
  $context['__theme_path'] = URLHelper::get_rel_url($theme->link(), true);

  return $context;
});
/** END **/
`;
  }
}
